# Allow bean definition overriding to resolve conflicts
spring.main.allow-bean-definition-overriding=true

# Server configuration
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus

# Logging
logging.level.com.smartcampus.hub=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
