spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: incident_ticket_db
  security:
    user:
      name: user
      password: password

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: INFO
